import type { AdminNavItem } from "@/features/admin/types/admin.types";

export const ADMIN_ROUTES = {
  dashboard: "/admin",
  bookings: "/admin/bookings",
  slots: "/admin/slots",
  pricing: "/admin/pricing",
  gallery: "/admin/gallery",
  media: "/admin/media",
  promotions: "/admin/promotions",
  events: "/admin/promotions",
  settings: "/admin/settings",
  reports: "/admin/reports",
  finance: "/admin/finance",
  customers: "/admin/customers",
  audit: "/admin/audit",
  emails: "/admin/emails",
  profile: "/admin/profile",
} as const;

export const ADMIN_NAV_ITEMS: AdminNavItem[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    href: ADMIN_ROUTES.dashboard,
    icon: "LayoutDashboard",
    permission: "dashboard.view",
  },
  {
    id: "bookings",
    label: "Bookings",
    href: ADMIN_ROUTES.bookings,
    icon: "CalendarDays",
    permission: "bookings.view",
  },
  {
    id: "slots",
    label: "Slots",
    href: ADMIN_ROUTES.slots,
    icon: "Clock",
    permission: "slots.view",
  },
  {
    id: "pricing",
    label: "Pricing",
    href: ADMIN_ROUTES.pricing,
    icon: "IndianRupee",
    permission: "pricing.view",
  },
  {
    id: "media",
    label: "Media",
    href: "/admin/media",
    icon: "Images",
    permission: "gallery.manage",
  },
  {
    id: "promotions",
    label: "Promotions",
    href: ADMIN_ROUTES.promotions,
    icon: "Sparkles",
    permission: "events.manage",
  },
  {
    id: "settings",
    label: "Business Settings",
    href: ADMIN_ROUTES.settings,
    icon: "Settings",
    permission: "settings.view",
  },
  {
    id: "reports",
    label: "Reports",
    href: ADMIN_ROUTES.reports,
    icon: "BarChart3",
    permission: "reports.view",
  },
  {
    id: "finance",
    label: "Finance",
    href: ADMIN_ROUTES.finance,
    icon: "Wallet",
    permission: "finance.view",
  },
  {
    id: "customers",
    label: "Customers",
    href: ADMIN_ROUTES.customers,
    icon: "Users",
    permission: "customers.view",
  },
  {
    id: "audit",
    label: "Audit Log",
    href: ADMIN_ROUTES.audit,
    icon: "ScrollText",
    permission: "audit.view",
  },
  {
    id: "emails",
    label: "Emails",
    href: ADMIN_ROUTES.emails,
    icon: "Mail",
    permission: "emails.view",
  },
  {
    id: "profile",
    label: "Profile",
    href: ADMIN_ROUTES.profile,
    icon: "UserCircle",
    permission: "profile.view",
  },
];

export const ADMIN_ROUTE_LABELS: Record<string, string> = {
  admin: "Dashboard",
  bookings: "Bookings",
  slots: "Slots",
  pricing: "Pricing",
  gallery: "Gallery",
  media: "Media",
  promotions: "Promotions",
  events: "Promotions",
  settings: "Business Settings",
  reports: "Reports",
  finance: "Finance",
  customers: "Customers",
  audit: "Audit Log",
  emails: "Communication Center",
  profile: "Profile",
};
