import { LandingPage } from "@/components/landing";
import { getLiveLandingStats } from "@/features/landing/services/landing-stats.service";
import { SettingsService } from "@/server/settings";

// Statically generated by default; without this the "By the numbers" stats
// would be frozen at whatever they were during the last build/deploy instead
// of reflecting real bookings. Refreshed in the background every 5 minutes.
export const revalidate = 300;

export default async function HomePage() {
  const [initialBusinessSettings, liveStats] = await Promise.all([
    SettingsService.getPublic(),
    getLiveLandingStats(),
  ]);

  return <LandingPage initialBusinessSettings={initialBusinessSettings} liveStats={liveStats} />;
}
